<?php

use Symfony\Component\HttpFoundation\Response;

/**
 * Alters the JSON:API response.
 *
 * @param array $jsonapi_response
 *   The decoded JSON data to be altered.
 * @param \Symfony\Component\HttpFoundation\Response $response
 *   The response.
 */
function jsonapi_assessment_jsonapi_response_alter(array &$jsonapi_response, Response $response) {
    // loop data to alter
    if (isset($jsonapi_response['data']) && is_Array($jsonapi_response['data'])) {
        $user = \Drupal::currentUser();

        foreach ($jsonapi_response['data'] as $key => $item) {
            if ($item['type'] == 'articles') {
                // load node to check permission
                $node = \Drupal\node\Entity\Node::load($item['attributes']['internalId']);
                $access = $node->access('update', $user);
                $jsonapi_response['data'][$key]['attributes']['editable'] = $access; // append attributes to display edit link in front end.
            }
        }
    }
}