<?php

use Symfony\Component\HttpFoundation\Response;

/**
 * Alters the JSON:API response.
 *
 * @param array $jsonapi_response
 *   The decoded JSON data to be altered.
 * @param \Symfony\Component\HttpFoundation\Response $response
 *   The response.
 */
function jsonapi_assessment_jsonapi_response_alter(array &$jsonapi_response, Response $response) {
    // loop data to alter
    if (isset($jsonapi_response['data']) && is_Array($jsonapi_response['data'])) {
        $entity_manager = \Drupal::entityTypeManager();
        $access_handler = $entity_manager->getAccessControlHandler('node');
        $access = $access_handler->createAccess('article');

        foreach ($jsonapi_response['data'] as $key => $item) {
            if ($item['type'] == 'articles') {
                $jsonapi_response['data'][$key]['attributes']['editable'] = $access; // append attributes to display edit link in front end.
            }
        }
    }
}